#!/bin/bash

mkdir -p ./lf/etau_0alpha_0beta_0/preprocess
mkdir -p ./lf/etau_0alpha_0beta_1/preprocess
mkdir -p ./lf/etau_0alpha_0beta_2/preprocess
mkdir -p ./lf/etau_0alpha_0beta_3/preprocess
mkdir -p ./lf/etau_0alpha_0beta_4/preprocess
mkdir -p ./lf/etau_0alpha_1beta_0/preprocess
mkdir -p ./lf/etau_0alpha_1beta_1/preprocess
mkdir -p ./lf/etau_0alpha_1beta_2/preprocess
mkdir -p ./lf/etau_0alpha_1beta_3/preprocess
mkdir -p ./lf/etau_0alpha_1beta_4/preprocess
mkdir -p ./lf/etau_0alpha_2beta_0/preprocess
mkdir -p ./lf/etau_0alpha_2beta_1/preprocess
mkdir -p ./lf/etau_0alpha_2beta_2/preprocess
mkdir -p ./lf/etau_0alpha_2beta_3/preprocess
mkdir -p ./lf/etau_0alpha_2beta_4/preprocess
mkdir -p ./lf/etau_0alpha_3beta_0/preprocess
mkdir -p ./lf/etau_0alpha_3beta_1/preprocess
mkdir -p ./lf/etau_0alpha_3beta_2/preprocess
mkdir -p ./lf/etau_0alpha_3beta_3/preprocess
mkdir -p ./lf/etau_0alpha_3beta_4/preprocess
mkdir -p ./lf/etau_0alpha_4beta_0/preprocess
mkdir -p ./lf/etau_0alpha_4beta_1/preprocess
mkdir -p ./lf/etau_0alpha_4beta_2/preprocess
mkdir -p ./lf/etau_0alpha_4beta_3/preprocess
mkdir -p ./lf/etau_0alpha_4beta_4/preprocess
mkdir -p ./lf/etau_1alpha_0beta_0/preprocess
mkdir -p ./lf/etau_1alpha_0beta_1/preprocess
mkdir -p ./lf/etau_1alpha_0beta_2/preprocess
mkdir -p ./lf/etau_1alpha_0beta_3/preprocess
mkdir -p ./lf/etau_1alpha_0beta_4/preprocess
mkdir -p ./lf/etau_1alpha_1beta_0/preprocess
mkdir -p ./lf/etau_1alpha_1beta_1/preprocess
mkdir -p ./lf/etau_1alpha_1beta_2/preprocess
mkdir -p ./lf/etau_1alpha_1beta_3/preprocess
mkdir -p ./lf/etau_1alpha_1beta_4/preprocess
mkdir -p ./lf/etau_1alpha_2beta_0/preprocess
mkdir -p ./lf/etau_1alpha_2beta_1/preprocess
mkdir -p ./lf/etau_1alpha_2beta_2/preprocess
mkdir -p ./lf/etau_1alpha_2beta_3/preprocess
mkdir -p ./lf/etau_1alpha_2beta_4/preprocess
mkdir -p ./lf/etau_1alpha_3beta_0/preprocess
mkdir -p ./lf/etau_1alpha_3beta_1/preprocess
mkdir -p ./lf/etau_1alpha_3beta_2/preprocess
mkdir -p ./lf/etau_1alpha_3beta_3/preprocess
mkdir -p ./lf/etau_1alpha_3beta_4/preprocess
mkdir -p ./lf/etau_1alpha_4beta_0/preprocess
mkdir -p ./lf/etau_1alpha_4beta_1/preprocess
mkdir -p ./lf/etau_1alpha_4beta_2/preprocess
mkdir -p ./lf/etau_1alpha_4beta_3/preprocess
mkdir -p ./lf/etau_1alpha_4beta_4/preprocess
mkdir -p ./lf/etau_2alpha_0beta_0/preprocess
mkdir -p ./lf/etau_2alpha_0beta_1/preprocess
mkdir -p ./lf/etau_2alpha_0beta_2/preprocess
mkdir -p ./lf/etau_2alpha_0beta_3/preprocess
mkdir -p ./lf/etau_2alpha_0beta_4/preprocess
mkdir -p ./lf/etau_2alpha_1beta_0/preprocess
mkdir -p ./lf/etau_2alpha_1beta_1/preprocess
mkdir -p ./lf/etau_2alpha_1beta_2/preprocess
mkdir -p ./lf/etau_2alpha_1beta_3/preprocess
mkdir -p ./lf/etau_2alpha_1beta_4/preprocess
mkdir -p ./lf/etau_2alpha_2beta_0/preprocess
mkdir -p ./lf/etau_2alpha_2beta_1/preprocess
mkdir -p ./lf/etau_2alpha_2beta_2/preprocess
mkdir -p ./lf/etau_2alpha_2beta_3/preprocess
mkdir -p ./lf/etau_2alpha_2beta_4/preprocess
mkdir -p ./lf/etau_2alpha_3beta_0/preprocess
mkdir -p ./lf/etau_2alpha_3beta_1/preprocess
mkdir -p ./lf/etau_2alpha_3beta_2/preprocess
mkdir -p ./lf/etau_2alpha_3beta_3/preprocess
mkdir -p ./lf/etau_2alpha_3beta_4/preprocess
mkdir -p ./lf/etau_2alpha_4beta_0/preprocess
mkdir -p ./lf/etau_2alpha_4beta_1/preprocess
mkdir -p ./lf/etau_2alpha_4beta_2/preprocess
mkdir -p ./lf/etau_2alpha_4beta_3/preprocess
mkdir -p ./lf/etau_2alpha_4beta_4/preprocess
mkdir -p ./lf/etau_3alpha_0beta_0/preprocess
mkdir -p ./lf/etau_3alpha_0beta_1/preprocess
mkdir -p ./lf/etau_3alpha_0beta_2/preprocess
mkdir -p ./lf/etau_3alpha_0beta_3/preprocess
mkdir -p ./lf/etau_3alpha_0beta_4/preprocess
mkdir -p ./lf/etau_3alpha_1beta_0/preprocess
mkdir -p ./lf/etau_3alpha_1beta_1/preprocess
mkdir -p ./lf/etau_3alpha_1beta_2/preprocess
mkdir -p ./lf/etau_3alpha_1beta_3/preprocess
mkdir -p ./lf/etau_3alpha_1beta_4/preprocess
mkdir -p ./lf/etau_3alpha_2beta_0/preprocess
mkdir -p ./lf/etau_3alpha_2beta_1/preprocess
mkdir -p ./lf/etau_3alpha_2beta_2/preprocess
mkdir -p ./lf/etau_3alpha_2beta_3/preprocess
mkdir -p ./lf/etau_3alpha_2beta_4/preprocess
mkdir -p ./lf/etau_3alpha_3beta_0/preprocess
mkdir -p ./lf/etau_3alpha_3beta_1/preprocess
mkdir -p ./lf/etau_3alpha_3beta_2/preprocess
mkdir -p ./lf/etau_3alpha_3beta_3/preprocess
mkdir -p ./lf/etau_3alpha_3beta_4/preprocess
mkdir -p ./lf/etau_3alpha_4beta_0/preprocess
mkdir -p ./lf/etau_3alpha_4beta_1/preprocess
mkdir -p ./lf/etau_3alpha_4beta_2/preprocess
mkdir -p ./lf/etau_3alpha_4beta_3/preprocess
mkdir -p ./lf/etau_3alpha_4beta_4/preprocess
