#!/bin/bash

mkdir -p ./hf_valid/etau_0alpha_5beta_0/anahist
mkdir -p ./hf_valid/etau_0alpha_5beta_0/reco2
mkdir -p ./hf_valid/etau_0alpha_5beta_1/anahist
mkdir -p ./hf_valid/etau_0alpha_5beta_1/reco2
mkdir -p ./hf_valid/etau_0alpha_5beta_2/anahist
mkdir -p ./hf_valid/etau_0alpha_5beta_2/reco2
mkdir -p ./hf_valid/etau_0alpha_5beta_3/anahist
mkdir -p ./hf_valid/etau_0alpha_5beta_3/reco2
mkdir -p ./hf_valid/etau_0alpha_5beta_4/anahist
mkdir -p ./hf_valid/etau_0alpha_5beta_4/reco2
mkdir -p ./hf_valid/etau_0alpha_6beta_0/anahist
mkdir -p ./hf_valid/etau_0alpha_6beta_0/reco2
mkdir -p ./hf_valid/etau_0alpha_6beta_1/anahist
mkdir -p ./hf_valid/etau_0alpha_6beta_1/reco2
mkdir -p ./hf_valid/etau_0alpha_6beta_2/anahist
mkdir -p ./hf_valid/etau_0alpha_6beta_2/reco2
mkdir -p ./hf_valid/etau_0alpha_6beta_3/anahist
mkdir -p ./hf_valid/etau_0alpha_6beta_3/reco2
mkdir -p ./hf_valid/etau_0alpha_6beta_4/anahist
mkdir -p ./hf_valid/etau_0alpha_6beta_4/reco2
mkdir -p ./hf_valid/etau_1alpha_5beta_0/anahist
mkdir -p ./hf_valid/etau_1alpha_5beta_0/reco2
mkdir -p ./hf_valid/etau_1alpha_5beta_1/anahist
mkdir -p ./hf_valid/etau_1alpha_5beta_1/reco2
mkdir -p ./hf_valid/etau_1alpha_5beta_2/anahist
mkdir -p ./hf_valid/etau_1alpha_5beta_2/reco2
mkdir -p ./hf_valid/etau_1alpha_5beta_3/anahist
mkdir -p ./hf_valid/etau_1alpha_5beta_3/reco2
mkdir -p ./hf_valid/etau_1alpha_5beta_4/anahist
mkdir -p ./hf_valid/etau_1alpha_5beta_4/reco2
mkdir -p ./hf_valid/etau_1alpha_6beta_0/anahist
mkdir -p ./hf_valid/etau_1alpha_6beta_0/reco2
mkdir -p ./hf_valid/etau_1alpha_6beta_1/anahist
mkdir -p ./hf_valid/etau_1alpha_6beta_1/reco2
mkdir -p ./hf_valid/etau_1alpha_6beta_2/anahist
mkdir -p ./hf_valid/etau_1alpha_6beta_2/reco2
mkdir -p ./hf_valid/etau_1alpha_6beta_3/anahist
mkdir -p ./hf_valid/etau_1alpha_6beta_3/reco2
mkdir -p ./hf_valid/etau_1alpha_6beta_4/anahist
mkdir -p ./hf_valid/etau_1alpha_6beta_4/reco2
mkdir -p ./hf_valid/etau_2alpha_5beta_0/anahist
mkdir -p ./hf_valid/etau_2alpha_5beta_0/reco2
mkdir -p ./hf_valid/etau_2alpha_5beta_1/anahist
mkdir -p ./hf_valid/etau_2alpha_5beta_1/reco2
mkdir -p ./hf_valid/etau_2alpha_5beta_2/anahist
mkdir -p ./hf_valid/etau_2alpha_5beta_2/reco2
mkdir -p ./hf_valid/etau_2alpha_5beta_3/anahist
mkdir -p ./hf_valid/etau_2alpha_5beta_3/reco2
mkdir -p ./hf_valid/etau_2alpha_5beta_4/anahist
mkdir -p ./hf_valid/etau_2alpha_5beta_4/reco2
mkdir -p ./hf_valid/etau_2alpha_6beta_0/anahist
mkdir -p ./hf_valid/etau_2alpha_6beta_0/reco2
mkdir -p ./hf_valid/etau_2alpha_6beta_1/anahist
mkdir -p ./hf_valid/etau_2alpha_6beta_1/reco2
mkdir -p ./hf_valid/etau_2alpha_6beta_2/anahist
mkdir -p ./hf_valid/etau_2alpha_6beta_2/reco2
mkdir -p ./hf_valid/etau_2alpha_6beta_3/anahist
mkdir -p ./hf_valid/etau_2alpha_6beta_3/reco2
mkdir -p ./hf_valid/etau_2alpha_6beta_4/anahist
mkdir -p ./hf_valid/etau_2alpha_6beta_4/reco2
mkdir -p ./hf_valid/etau_3alpha_5beta_0/anahist
mkdir -p ./hf_valid/etau_3alpha_5beta_0/reco2
mkdir -p ./hf_valid/etau_3alpha_5beta_1/anahist
mkdir -p ./hf_valid/etau_3alpha_5beta_1/reco2
mkdir -p ./hf_valid/etau_3alpha_5beta_2/anahist
mkdir -p ./hf_valid/etau_3alpha_5beta_2/reco2
mkdir -p ./hf_valid/etau_3alpha_5beta_3/anahist
mkdir -p ./hf_valid/etau_3alpha_5beta_3/reco2
mkdir -p ./hf_valid/etau_3alpha_5beta_4/anahist
mkdir -p ./hf_valid/etau_3alpha_5beta_4/reco2
mkdir -p ./hf_valid/etau_3alpha_6beta_0/anahist
mkdir -p ./hf_valid/etau_3alpha_6beta_0/reco2
mkdir -p ./hf_valid/etau_3alpha_6beta_1/anahist
mkdir -p ./hf_valid/etau_3alpha_6beta_1/reco2
mkdir -p ./hf_valid/etau_3alpha_6beta_2/anahist
mkdir -p ./hf_valid/etau_3alpha_6beta_2/reco2
mkdir -p ./hf_valid/etau_3alpha_6beta_3/anahist
mkdir -p ./hf_valid/etau_3alpha_6beta_3/reco2
mkdir -p ./hf_valid/etau_3alpha_6beta_4/anahist
mkdir -p ./hf_valid/etau_3alpha_6beta_4/reco2
